    export class Selectors {
       
    username='//*[@name="Login-LoginScreen-LoginDV-username"]';
    password='//*[@name="Login-LoginScreen-LoginDV-password"]';
    login="//*[@id='Login-LoginScreen-LoginDV-submit']";
    Accountab="//div[@id='TabBar-AccountTab']";
    newsubmission="//div[@id='AccountFile_Summary-AccountSummaryDashboard-OpenPolicyTransactionsAccountListViewTile-NewSubmission']";
    Workerscompselect= "//td[@id ='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-6-Select']";
    Qustion1= "(//div[@class='gw-radioDiv'])[1]";
    Question3 = "(//div[@class='gw-radioDiv'])[3]"
    Totalanaulamount ="//input[@name='SubmissionWizard-SubmissionWizard_PreQualificationScreen-PreQualQuestionSetsDV-QuestionSetsDV-0-QuestionSetLV-4-QuestionModalInput-IntegerFieldInput_NoPost']";
    NextQuali="//div[@id='SubmissionWizard-Next']";
    Datequote ="//input[@class='gw-min-visible gw-DateValueWidget--dateInput']";
    Estprimenm = "//input[@name='SubmissionWizard-LOBWizardStepGroup-SubmissionWizard_PolicyInfoScreen-SubmissionWizard_PolicyInfoDV-estimatedPremiumInput']";
    SSN= "//input[@name='SubmissionWizard-LOBWizardStepGroup-SubmissionWizard_PolicyInfoScreen-SubmissionWizard_PolicyInfoDV-AccountInfoInputSet-PolicyOfficialIDInputSet-OfficialIDDV_Input']";
    Industrialcode ="//input[@name='SubmissionWizard-LOBWizardStepGroup-SubmissionWizard_PolicyInfoScreen-SubmissionWizard_PolicyInfoDV-AccountInfoInputSet-IndustryCode']";
    deleteSSNdropdown="//div[@class='gw-PrivacyValueWidget--dropMenu gw-isTopLevelMenu gw-hasChildren gw-putSubMenusBelow gw-action--outer']";
    deleteSSN= "(//div[@data-gw-click='gwPrivacy.clearValue id:SubmissionWizard-LOBWizardStepGroup-SubmissionWizard_PolicyInfoScreen-SubmissionWizard_PolicyInfoDV-AccountInfoInputSet-PolicyOfficialIDInputSet-OfficialIDDV_Input'])[1]";
    WCcovAddClass="//div[@class='gw-AddButtonWidget gw-styleTag--ToolbarWidget gw-ToolbarButtonWidget gw-putSubMenusBelow gw-isTopLevelMenu gw-hasMinimizedView gw-action--outer']";
    WClocation="//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WorkersCompCoverageConfigScreen-WorkersCompCoverageCV-WorkersCompClassesInputSet-WCCovEmpLV-0-Loc']";
    WClocationselect="//option[@value='PolicyLocation:530']";
    classSearchclick="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WorkersCompCoverageConfigScreen-WorkersCompCoverageCV-WorkersCompClassesInputSet-WCCovEmpLV-0-ClassCode-SelectClassCode']";
    Classnamesearhtext="//input[@name='WCClassCodeSearchPopup-WCClassCodeSearchScreen-WCClassCodeSearchDV-Code']";
    ClassnameSearch ="//div[@id='WCClassCodeSearchPopup-WCClassCodeSearchScreen-WCClassCodeSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search']";
    Classnameselect="//td[@id='WCClassCodeSearchPopup-WCClassCodeSearchScreen-ClassCodeSearchResultsLV-0-1']";
    employee="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WorkersCompCoverageConfigScreen-WorkersCompCoverageCV-WorkersCompClassesInputSet-WCCovEmpLV-0-NumEmployees']";
    basicamount="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WorkersCompCoverageConfigScreen-WorkersCompCoverageCV-WorkersCompClassesInputSet-WCCovEmpLV-0-AnnualRenum']";
    Errormessage="//div[@class='gw-message-and-suffix']";
    Supplementalclick="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WorkersCompSupplementalScreen-QuestionSetsDV-0-QuestionSetLV-0-QuestionModalInput-BooleanRadioInput_NoPost_0']";
    Addoption="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-OptionIteratorButton']";
    FederalLiab="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-OptionIteratorButton-0-CurrentOption']";
    AddFederalClass="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-WCOptionCardPanelSet-WCFederalLiabilityInputSet-WCLine_WCCovEmpLV_tb-Add']";
    locationFederal="//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-WCOptionCardPanelSet-WCFederalLiabilityInputSet-WCLine_WCCovEmpLV-0-Loc']";
    ClasscodeFeb="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-WCOptionCardPanelSet-WCFederalLiabilityInputSet-WCLine_WCCovEmpLV-0-ClassCode-SelectClassCode']";
    ClassCodeSearchTextbox="//input[@name='WCClassCodeSearchPopup-WCClassCodeSearchScreen-WCClassCodeSearchDV-Code']";
    ClassCodeSearchClick="//div[@id='WCClassCodeSearchPopup-WCClassCodeSearchScreen-WCClassCodeSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search']";
    ClassCodeSelect="//div[@id='WCClassCodeSearchPopup-WCClassCodeSearchScreen-ClassCodeSearchResultsLV-0-_Select']";
    BasicFrdamount ="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CoverageOptionsScreen-WCOptionsPanelSet-WCOptionCardPanelSet-WCFederalLiabilityInputSet-WCLine_WCCovEmpLV-0-AnnualRenum']";
    AddContingency ="//div[@id='SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV_tb-AddNewContingencyButton']";
    title="//input[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyTitle']";
    description="//textarea[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyDescription']";
    Select="//select[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyAction']";
    Duedate= "//input[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyDueDate']";
    Ok ="//div[@class='gw-ToolbarButtonWidget gw-styleTag--ToolbarWidget gw-putSubMenusBelow gw-isTopLevelMenu gw-hasMinimizedView gw-action--outer']";
    Closeoption ="//div[@id='SubmissionWizard-SubmissionWizard_PolicyReviewScreen-JobWizardToolbarButtonSet-CloseOptions']";
    Withdraw="//div[@id='SubmissionWizard-SubmissionWizard_PolicyReviewScreen-JobWizardToolbarButtonSet-CloseOptions-WithdrawJob']";
    GeneralLiab="//td[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-3-Select']";
    offeringSelection="//select[@name='SubmissionWizard-OfferingScreen-OfferingSelection']";
    GLPreQualification="//div[@id='SubmissionWizard-SubmissionWizard_PreQualificationScreen-PreQualQuestionSetsDV-QuestionSetsDV-0-QuestionSetLV-0-QuestionModalInput-BooleanRadioInput_NoPost_1']";
    AdditionalCoverages="//div[@aria-controls='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityScreen-GeneralLiability_AdditionalCoveragesCard']";
    AddCoverage="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityScreen-AdditionalCoveragesPanelSet-AdditionalCoveragesDV_tb-Add']";
    SelectCat="//select[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchDV-CoverageCategory']";
    SearchGL="//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search']";
    EmploymentCoverage="//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-0-_Checkbox']";
    AddSelecedCoverages="//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV_tb-AddCoverageButton']";
    Addexposure ="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityEUScreen-GeneralLiabilityEUDV-SubmissionWizard_GL_ExposureUnitsLV_tb-Add']";
    Addlocation= "//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityEUScreen-GeneralLiabilityEUDV-SubmissionWizard_GL_ExposureUnitsLV-0-Location']";
    ExposureClassCodeSearch="//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityEUScreen-GeneralLiabilityEUDV-SubmissionWizard_GL_ExposureUnitsLV-0-ClassCode-SelectClassCode']";
    Addclass="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityEUScreen-GeneralLiabilityEUDV-SubmissionWizard_GL_ExposureUnitsLV-0-ClassCode']";
    Addbasicamount="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GeneralLiabilityEUScreen-GeneralLiabilityEUDV-SubmissionWizard_GL_ExposureUnitsLV-0-BasisAmount']";
    AddGLmodifierExp="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-ModifiersScreen-WCModifiersInputSet-ModIteratorEligible-0-EligibilityInputGroup-ModifierInput']";
    Locationinside="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-ModifiersScreen-ScheduleRateDV-0-ScheduleRateLV-0-CreditDebit']";
    jsutificationlocationinsider="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-ModifiersScreen-ScheduleRateDV-0-ScheduleRateLV-0-Justification']";
    safetyorg="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-ModifiersScreen-ScheduleRateDV-0-ScheduleRateLV-7-CreditDebit']";
    justificationsafety="//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-ModifiersScreen-ScheduleRateDV-0-ScheduleRateLV-7-Justification']";
    AddcontigencyTitle="//input[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyTitle']";
    AddContigencayDesc="//textarea[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyDescription']";
    AddContigencayAction="//div[@id='NewContingencyPopup-BaseContingencyInfoDV-ContingencyAction']";
    Action="//select[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyAction']";
    duedateAddCont="//input[@name='NewContingencyPopup-BaseContingencyInfoDV-ContingencyDueDate']";
  }